[ClassVersion("1.0"), FriendlyName("cWMIEventBinding")]
class cWMIEventBinding : OMI_BaseResource 
{
	[Key] string Filter;
	[Key] string Consumer;
	[Write] Boolean SlowDownProviders;
	[Write] Boolean MaintainSecurityContext;
	[Write] uint32 DeliveryQoS;
	[Required, ValueMap{"LogFile", "EventLog","CommandLine","Script","SMTP"},Values{"LogFile", "EventLog","CommandLine","Script","SMTP"}] string ConsumerType;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};