ConvertFrom-StringData @'    
    NoHyperVModule=Hyper-V PowerShell Module not found.
    CheckSETMembers=Checking if SET network adapter members match or not.
    TeamMembersUpdate=SET Network Adapter members mismatch. This will be updated.
    LBUpdate=SET load balancing mode is different. It will be updated.
    TeamingModeUpdate=SET teaming mode is differet. It will be updated.
    UpdatingSETeam=Updating SET configuration as requested.
    UpdateAllowManagementOS=Updating AllowManagementOS on the VM switch associated with the SET.
    IOVcannotbeUpdated=EnableIOV cannot be updated once SET is created. Ignoring this change in configuration.
    ReservationModeCannotBeUpdated=Reservation mode cannot be updated once SET is created. Ignoring this change in configuration.
    PacketDirectCannotBeUpdated=Packet Direct cannot be updated once SET is created. Ignoring this change in configuration.
    CheckNetAdapter=Checking if network adapter specified is a part of another VM switch.
    SwitchWithNameExists=Another switch with specified name already exists. It is not recommeded to use the same name for mulitple switches.
    UsedAdapter=One of the adapters in the specified SET configuration is being used in another switch.
    CreateSET=Creating SwitchEmbeddedTeam.
    UpdateSET=Updating SwitchEmbeddedTeam.
    RemoveSET=Removing SwitchEmbeddedTeam.
    CheckSwitchExists=Checking if SET already exists.
    SETMembersDontMatch=SET members don't match. This team will be updated.
    CheckSETIOV=Checking if IOV is enabled.
    CheckSETReservationMode=Checking if reservation mode is configured as desired.
    CheckSETEnablePacketDirect=Checking if packet direct is enabled.
    CheckSETLoadBalacing=Checking if load balancing mode is configured as desired.
    CheckSETTeamingMode=Checking if SET teaming mode is configured as desired.
    SwitchConfigPresentNoAction=Switch configuration present as desired. No action needed.
    SwitchPresentRemove=Switch team is present while it should not. It will be removed.
    SwitchNotPresentCreate=Switch team does not exist. It will be created.
    SwitchNotPresentNoAction=Switch team exists. No action needed.
    SwitchNotPresent=Switch is not present.
    CheckSETAllowManagementOS=Checking if AllowManagementOS configurtion is present.
'@