[ClassVersion("1.0"), FriendlyName("WMIActiveScriptConsumer")]
class WMIActiveScriptConsumer : OMI_BaseResource 
{
	[Key] string Name;
	[Write] string ScriptFileName;
    	[Write] string ScriptText;
    	[Write] string ScriptingEngine;
    	[Write] uint32 MaximumQueueSize;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};